-- Addie Image Library
-- Searchable image asset registry with search event logging for gap detection

-- Image assets: approved illustrations Addie can use in conversations
CREATE TABLE IF NOT EXISTS addie_images (
  id SERIAL PRIMARY KEY,
  filename TEXT NOT NULL,
  alt_text TEXT NOT NULL,
  topics TEXT[] NOT NULL DEFAULT '{}',
  category TEXT NOT NULL DEFAULT 'walkthrough',  -- walkthrough, concept, diagram, scene
  characters TEXT[] NOT NULL DEFAULT '{}',        -- character names from the bible
  description TEXT,                                -- longer description for search matching
  image_url TEXT NOT NULL,                         -- full URL to the image
  approved BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(filename)
);

-- Image search events: every time Addie searches for images
-- Usage tracking and gap requests are derived from tool execution logs
-- in the Threads view rather than requiring separate tools.
CREATE TABLE IF NOT EXISTS addie_image_searches (
  id SERIAL PRIMARY KEY,
  query TEXT NOT NULL,                             -- what Addie searched for
  intent TEXT,                                     -- why she searched (conversation context)
  context_type TEXT NOT NULL DEFAULT 'conversation', -- conversation, certification, channel
  thread_id TEXT,                                  -- Slack thread if available
  slack_user_id TEXT,                              -- who was she talking to
  results_returned INTEGER NOT NULL DEFAULT 0,     -- how many images matched
  result_ids INTEGER[],                            -- which image IDs were returned
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_addie_images_topics ON addie_images USING GIN(topics);
CREATE INDEX IF NOT EXISTS idx_addie_images_category ON addie_images(category);
CREATE INDEX IF NOT EXISTS idx_addie_images_approved ON addie_images(approved);
CREATE INDEX IF NOT EXISTS idx_addie_image_searches_created ON addie_image_searches(created_at);
CREATE INDEX IF NOT EXISTS idx_addie_image_searches_results ON addie_image_searches(results_returned);

-- Seed with existing illustrations
-- Includes descriptions for search matching, enriched topic tags, and character attributions
INSERT INTO addie_images (filename, alt_text, description, topics, category, characters, image_url) VALUES
  -- Concept diagrams
  ('budget-commitment-phases.png', 'Budget commitment phases from proposal through reconciliation', 'Shows the lifecycle of budget commitment in a media buy: proposal, reservation, confirmation, delivery, and reconciliation phases with amounts at each stage', ARRAY['media-buy', 'media-buy-lifecycle', 'budget', 'create-media-buy'], 'concept', '{}', 'https://docs.adcontextprotocol.org/images/concepts/budget-commitment-phases.png'),
  ('ecosystem-layers.png', 'AdCP ecosystem layers from protocol through applications', 'Architecture diagram showing protocol layer, transport layer, agent layer, and application layer and how they stack', ARRAY['protocol-overview', 'architecture', 'multi-agent'], 'concept', '{}', 'https://docs.adcontextprotocol.org/images/concepts/ecosystem-layers.png'),
  ('media-buy-lifecycle.png', 'Media buy lifecycle from discovery through delivery', 'End-to-end media buy lifecycle: product discovery, proposal, creative sync, campaign launch, monitoring, delivery reporting', ARRAY['media-buy', 'media-buy-lifecycle', 'get-products', 'create-media-buy', 'delivery'], 'concept', '{}', 'https://docs.adcontextprotocol.org/images/concepts/media-buy-lifecycle.png'),
  ('protocol-domain-map.png', 'Map of AdCP protocol domains and their relationships', 'Shows the five AdCP domains (media buy, creative, governance, signals, brand) and how they interconnect', ARRAY['protocol-overview', 'architecture', 'media-buy', 'creative', 'governance', 'signals'], 'concept', '{}', 'https://docs.adcontextprotocol.org/images/concepts/protocol-domain-map.png'),
  ('three-party-governance.png', 'Three-party governance model between buyer, seller, and governance agent', 'Illustrates how the governance agent sits between buyer and seller agents to enforce rules, check compliance, and escalate to humans', ARRAY['governance', 'campaign-governance', 'compliance', 'brand-safety', 'human-in-the-loop'], 'concept', '{}', 'https://docs.adcontextprotocol.org/images/concepts/three-party-governance.png'),
  -- Walkthrough diagrams
  ('diagram-five-protocols.png', 'The five AdCP protocols and how they connect', 'Overview diagram showing media buy, creative, governance, signals, and brand protocol domains with arrows showing data flow between them', ARRAY['protocol-overview', 'media-buy', 'governance', 'creative', 'signals', 'architecture'], 'diagram', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/diagram-five-protocols.png'),
  ('diagram-format-manifest-render.png', 'How formats define slots, manifests fill them, and the result renders', 'Technical diagram of the creative pipeline: format defines available slots and dimensions, manifest maps assets to slots, render produces the final creative', ARRAY['creative-formats', 'creative-manifests', 'creative-workflow', 'list-creative-formats'], 'diagram', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/diagram-format-manifest-render.png'),
  ('diagram-generative-tiers.png', 'Tier 1 static, Tier 2 optimized, Tier 3 AI-generated creative', 'Progression from pre-built static assets through optimization to fully AI-generated creative content', ARRAY['generative-creative', 'creative-workflow', 'ai-creative'], 'diagram', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/diagram-generative-tiers.png'),
  ('diagram-governance-triangle.png', 'Three-party governance: buyer, seller, and independent governance agent', 'Shows the triangular relationship where a governance agent independently validates campaign plans between buyer and seller', ARRAY['governance', 'campaign-governance', 'compliance', 'brand-safety', 'human-in-the-loop'], 'diagram', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/diagram-governance-triangle.png'),
  ('diagram-orchestrator-sequence.png', 'Orchestrator API flow: capabilities, formats, build, sync, delivery', 'Sequence diagram of orchestrator communicating with creative agents: discover capabilities, list formats, build creative, sync to sellers, collect delivery data', ARRAY['orchestration', 'creative-workflow', 'multi-agent'], 'diagram', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/diagram-orchestrator-sequence.png'),
  ('diagram-01-format-discovery.png', 'Agency platform discovers formats from three sellers', 'Agency buyer agent queries three different seller agents for their supported creative formats', ARRAY['creative-formats', 'creative-workflow', 'orchestration', 'list-creative-formats'], 'diagram', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/diagram-01-format-discovery.png'),
  ('diagram-02-generate-route.png', 'Brief routed to video, display, and social agents', 'Creative brief is distributed to specialized agents for each format type: video, display, social', ARRAY['creative-workflow', 'generative-creative', 'orchestration', 'build-creative'], 'diagram', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/diagram-02-generate-route.png'),
  ('diagram-03-distribute.png', 'Creatives distributed via sync_creatives to sellers', 'Generated creatives are synced to seller platforms using the sync_creatives task', ARRAY['creative-workflow', 'orchestration', 'sync-creatives'], 'diagram', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/diagram-03-distribute.png'),
  ('diagram-04-delivery-aggregation.png', 'Delivery data collected from three sellers and merged', 'Delivery reporting data from multiple sellers aggregated into a unified view', ARRAY['creative-delivery', 'creative-workflow', 'orchestration', 'reporting', 'measurement'], 'diagram', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/diagram-04-delivery-aggregation.png'),
  ('diagram-05-lifecycle.png', 'Full creative lifecycle from brief to delivery and back', 'Complete loop: brief creation, format discovery, creative generation, distribution, delivery tracking, optimization', ARRAY['creative-workflow', 'protocol-overview'], 'diagram', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/diagram-05-lifecycle.png'),
  -- Creative walkthrough scenes (Maya)
  ('panel-01-strategist-desk.png', 'A creative strategist reviews ad mockups across formats', 'Maya at her desk reviewing display, video, and social ad mockups on multiple screens', ARRAY['creative-workflow'], 'scene', ARRAY['Maya'], 'https://docs.adcontextprotocol.org/images/walkthrough/panel-01-strategist-desk.png'),
  ('panel-02-brief-radiates.png', 'A creative brief radiates to TV, phone, laptop, and billboard', 'A single creative brief document with lines radiating out to different device and format types', ARRAY['creative-workflow', 'build-creative'], 'scene', ARRAY['Maya'], 'https://docs.adcontextprotocol.org/images/walkthrough/panel-02-brief-radiates.png'),
  ('panel-03-agents-collaborate.png', 'Three AI agents collaborate at a workbench', 'Video, display, and social creative agents working together at a shared workbench', ARRAY['multi-agent', 'orchestration', 'ai-creative'], 'scene', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/panel-03-agents-collaborate.png'),
  ('panel-04-draft-to-production.png', 'Draft mockup transforms into polished production creative', 'Side-by-side showing a rough wireframe draft transforming into polished production-ready creative', ARRAY['creative-workflow', 'generative-creative'], 'scene', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/panel-04-draft-to-production.png'),
  ('panel-05-distribute.png', 'Strategist presses Launch while publisher connections light up', 'A strategist at a control panel pressing launch, with lines connecting to publisher platforms lighting up', ARRAY['sync-creatives', 'creative-workflow'], 'scene', ARRAY['Maya'], 'https://docs.adcontextprotocol.org/images/walkthrough/panel-05-distribute.png'),
  ('panel-06-delivery-dashboard.png', 'Unified dashboard merging data from three sellers', 'Dashboard screen showing metrics from three different sellers consolidated into unified performance view', ARRAY['creative-delivery', 'creative-workflow', 'reporting', 'measurement'], 'scene', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/panel-06-delivery-dashboard.png'),
  ('panel-07-variant-replay.png', 'Grid of ad variants with performance ratings', 'Grid of creative variants each showing performance scores, enabling comparison of what worked', ARRAY['creative-delivery', 'generative-creative', 'measurement'], 'scene', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/panel-07-variant-replay.png'),
  -- Media buy walkthrough scenes (Sam)
  ('media-buy-01-sams-desk.png', 'Sam at a media operations desk managing campaigns', 'Sam managing multiple campaign windows and spreadsheets across several monitors', ARRAY['media-buy', 'media-buy-lifecycle'], 'scene', ARRAY['Sam'], 'https://docs.adcontextprotocol.org/images/walkthrough/media-buy-01-sams-desk.png'),
  ('media-buy-02-brief-radiates.png', 'A campaign brief broadcasting to multiple sellers', 'Campaign brief document sending queries to multiple seller agents simultaneously', ARRAY['media-buy', 'media-buy-lifecycle', 'get-products', 'product-discovery'], 'scene', ARRAY['Sam'], 'https://docs.adcontextprotocol.org/images/walkthrough/media-buy-02-brief-radiates.png'),
  ('media-buy-03-proposals.png', 'Comparing proposals from multiple sellers side by side', 'Side-by-side comparison of seller proposals with pricing, audience, and inventory details', ARRAY['media-buy', 'media-buy-lifecycle', 'get-products', 'product-discovery'], 'scene', ARRAY['Sam'], 'https://docs.adcontextprotocol.org/images/walkthrough/media-buy-03-proposals.png'),
  ('media-buy-04-creatives.png', 'Creative assets adapted to each seller format', 'Creative assets being automatically reformatted for each seller platform requirements', ARRAY['media-buy', 'media-buy-lifecycle', 'creative-workflow', 'sync-creatives'], 'scene', ARRAY['Sam'], 'https://docs.adcontextprotocol.org/images/walkthrough/media-buy-04-creatives.png'),
  ('media-buy-05-launch.png', 'Campaign launching across multiple platforms simultaneously', 'Campaign going live on CTV, display, and social platforms at the same time', ARRAY['media-buy', 'media-buy-lifecycle', 'create-media-buy'], 'scene', ARRAY['Sam'], 'https://docs.adcontextprotocol.org/images/walkthrough/media-buy-05-launch.png'),
  ('media-buy-06-governance.png', 'Governance agent reviewing campaign before execution', 'Governance agent checking budget limits, brand safety, and compliance before campaign goes live', ARRAY['media-buy', 'governance', 'campaign-governance', 'compliance', 'brand-safety'], 'scene', ARRAY['Sam'], 'https://docs.adcontextprotocol.org/images/walkthrough/media-buy-06-governance.png'),
  ('media-buy-07-delivery.png', 'Unified delivery dashboard aggregating results from sellers', 'Dashboard consolidating impressions, clicks, and spend from multiple seller platforms', ARRAY['media-buy', 'media-buy-lifecycle', 'delivery', 'reporting', 'measurement'], 'scene', ARRAY['Sam'], 'https://docs.adcontextprotocol.org/images/walkthrough/media-buy-07-delivery.png'),
  -- Governance walkthrough scenes (Jordan)
  ('governance-01-no-oversight.png', 'Robot reaching for BUY button with no human oversight', 'A buying robot about to press a BUY button with no checks or guardrails in place', ARRAY['governance', 'campaign-governance', 'human-in-the-loop'], 'scene', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/governance-01-no-oversight.png'),
  ('governance-02-plan-synced.png', 'Buying robot sends campaign plan to governance robot', 'A buyer agent sending a campaign plan to a governance agent for review', ARRAY['governance', 'campaign-governance'], 'scene', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/governance-02-plan-synced.png'),
  ('governance-03-checks.png', 'Governance robot reviews budget, brand safety, and compliance panels', 'Governance agent examining three panels: budget limits, brand safety rules, and regulatory compliance', ARRAY['governance', 'campaign-governance', 'brand-safety', 'compliance', 'budget'], 'scene', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/governance-03-checks.png'),
  ('governance-04-escalation.png', 'Governance robot escalates flagged plan to a human reviewer', 'Governance agent flagging an issue and passing the decision to a human for review', ARRAY['governance', 'campaign-governance', 'human-in-the-loop', 'escalation'], 'scene', ARRAY['Jordan'], 'https://docs.adcontextprotocol.org/images/walkthrough/governance-04-escalation.png'),
  ('governance-05-approved.png', 'Human approves plan with conditions attached', 'A human reviewer approving a campaign plan with specific conditions noted', ARRAY['governance', 'campaign-governance', 'human-in-the-loop'], 'scene', ARRAY['Jordan'], 'https://docs.adcontextprotocol.org/images/walkthrough/governance-05-approved.png'),
  ('governance-06-running.png', 'Governance robot monitors running campaigns from a watchtower', 'Governance agent watching live campaign metrics from an elevated monitoring position', ARRAY['governance', 'campaign-governance', 'monitoring'], 'scene', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/governance-06-running.png'),
  ('governance-07-audit-trail.png', 'Timeline of decisions presented as an audit trail', 'Chronological log of all governance decisions, approvals, escalations, and overrides', ARRAY['governance', 'campaign-governance', 'audit', 'compliance'], 'scene', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/governance-07-audit-trail.png'),
  -- Signals walkthrough scenes (Sam + Kai)
  ('signals-01-planner-brief.png', 'Planner writing an audience brief', 'A media planner drafting an audience targeting brief with demographic and interest criteria', ARRAY['signals', 'audience-signals', 'audience-targeting'], 'scene', ARRAY['Sam'], 'https://docs.adcontextprotocol.org/images/walkthrough/signals-01-planner-brief.png'),
  ('signals-02-natural-language-search.png', 'Natural language search for audience signals', 'Typing a natural language query to discover available audience signal data from providers', ARRAY['signals', 'audience-signals', 'signal-discovery'], 'scene', ARRAY['Sam'], 'https://docs.adcontextprotocol.org/images/walkthrough/signals-02-natural-language-search.png'),
  ('signals-03-results-materialize.png', 'Signal search results appearing', 'Search results showing available audience segments from multiple signal providers', ARRAY['signals', 'audience-signals', 'signal-discovery'], 'scene', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/signals-03-results-materialize.png'),
  ('signals-04-activation-flow.png', 'Signal activation workflow', 'Activating selected audience signals for use in campaign targeting', ARRAY['signals', 'audience-signals', 'signal-activation'], 'scene', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/signals-04-activation-flow.png'),
  ('signals-05-campaign-targeting.png', 'Campaign targeting with activated signal data', 'Campaign setup using activated signal data for precise audience targeting', ARRAY['signals', 'audience-signals', 'audience-targeting', 'signal-activation'], 'scene', ARRAY['Sam'], 'https://docs.adcontextprotocol.org/images/walkthrough/signals-05-campaign-targeting.png'),
  ('signals-06-ecosystem-view.png', 'Signal ecosystem overview showing providers and consumers', 'Bird''s eye view of signal providers (data companies) connected to signal consumers (buyer agents)', ARRAY['signals', 'audience-signals', 'signal-ecosystem'], 'scene', ARRAY['Kai'], 'https://docs.adcontextprotocol.org/images/walkthrough/signals-06-ecosystem-view.png'),
  -- AdCP intro walkthrough scenes (Alex)
  ('adcp-01-fragmentation.png', 'Twelve different platform interfaces with tangled connections', 'A media buyer overwhelmed by twelve different ad platform dashboards connected by tangled wires', ARRAY['protocol-overview', 'fragmentation'], 'scene', ARRAY['Alex'], 'https://docs.adcontextprotocol.org/images/walkthrough/adcp-01-fragmentation.png'),
  ('adcp-02-one-protocol.png', 'Hexagonal protocol hub connecting all platform types', 'Single AdCP protocol hub at center with clean connections to CTV, display, social, audio platforms', ARRAY['protocol-overview', 'architecture'], 'scene', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/adcp-02-one-protocol.png'),
  ('adcp-03-agents.png', 'Five specialized robots collaborating around a shared workspace', 'Five agent types (buyer, seller, creative, governance, signals) working together at a round table', ARRAY['protocol-overview', 'multi-agent', 'architecture'], 'scene', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/adcp-03-agents.png'),
  ('adcp-04-workflow.png', 'Agent workflow from brief to live ads across a city skyline', 'Campaign flowing from brief through agent collaboration to live ads displayed across a city skyline', ARRAY['protocol-overview', 'media-buy-lifecycle'], 'scene', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/adcp-04-workflow.png'),
  ('adcp-05-governance.png', 'Guardian robot inspecting campaign blueprints at a checkpoint', 'A governance agent at a checkpoint inspecting campaign plans before allowing execution', ARRAY['protocol-overview', 'governance', 'campaign-governance', 'compliance'], 'scene', '{}', 'https://docs.adcontextprotocol.org/images/walkthrough/adcp-05-governance.png')
ON CONFLICT (filename) DO NOTHING;
