/**
 * Publisher profiles for the training agent.
 *
 * Each profile defines a fictional publisher with realistic properties,
 * channels, pricing models, and measurement capabilities. The product
 * factory uses these to generate schema-compliant products.
 */

import type { PublisherProfile } from './types.js';

export const PUBLISHERS: PublisherProfile[] = [
  {
    id: 'pinnacle_news',
    name: 'Pinnacle News Group',
    domain: 'pinnaclenews.example',
    description: 'Premium news and entertainment publisher with web, mobile, and CTV inventory across award-winning journalism and lifestyle content.',
    channels: ['display', 'olv', 'ctv', 'email'],
    deliveryTypes: ['guaranteed', 'non_guaranteed'],
    pricingTemplates: [
      { model: 'cpm', currency: 'USD', floorPrice: 4, priceGuidance: { suggested: 8, range: { min: 4, max: 18 } } },
      { model: 'vcpm', currency: 'USD', floorPrice: 6, priceGuidance: { suggested: 12, range: { min: 6, max: 22 } } },
      { model: 'cpm', currency: 'USD', fixedPrice: 15, minSpendPerPackage: 5000 },
      { model: 'cpm', currency: 'EUR', floorPrice: 4, priceGuidance: { suggested: 7, range: { min: 4, max: 16 } } },
    ],
    measurementProvider: 'Google Ad Manager with IAS viewability',
    measurementNotes: 'MRC-accredited viewability. 50% in-view for 1s display / 2s video. GroupM standard available on request.',
    reportingFrequencies: ['daily', 'monthly'],
    reportingMetrics: ['impressions', 'spend', 'clicks', 'ctr', 'viewability', 'video_completions', 'completion_rate'],
    properties: [
      {
        propertyId: 'pinnacle_web',
        name: 'Pinnacle News Website',
        identifierType: 'domain',
        identifierValue: 'pinnaclenews.example',
        channels: ['display', 'olv'],
        tags: ['news', 'premium', 'web'],
      },
      {
        propertyId: 'pinnacle_app',
        name: 'Pinnacle News App',
        identifierType: 'app_bundle',
        identifierValue: 'com.pinnaclenews.app',
        channels: ['display', 'olv'],
        tags: ['news', 'premium', 'mobile'],
      },
      {
        propertyId: 'pinnacle_ctv',
        name: 'Pinnacle Streaming',
        identifierType: 'app_bundle',
        identifierValue: 'com.pinnaclenews.ctv',
        channels: ['ctv'],
        tags: ['news', 'premium', 'ctv', 'streaming'],
      },
    ],
  },

  {
    id: 'wavelength',
    name: 'Wavelength Audio',
    domain: 'wavelengthaudio.example',
    description: 'Digital audio streaming platform with music, podcast, and live radio inventory reaching 40M monthly listeners.',
    channels: ['streaming_audio', 'podcast'],
    deliveryTypes: ['guaranteed', 'non_guaranteed'],
    pricingTemplates: [
      { model: 'cpm', currency: 'USD', floorPrice: 8, priceGuidance: { suggested: 10, range: { min: 8, max: 15 } } },
      { model: 'flat_rate', currency: 'USD', fixedPrice: 15000, minSpendPerPackage: 5000 },
    ],
    measurementProvider: 'Podtrac certified measurement with Nielsen DAR',
    measurementNotes: 'IAB 2.1 compliant podcast measurement. Audio completions tracked via SDK. Host-read verification via transcript matching.',
    reportingFrequencies: ['daily', 'monthly'],
    reportingMetrics: ['impressions', 'spend', 'completion_rate', 'reach', 'frequency'],
    properties: [
      {
        propertyId: 'wavelength_app',
        name: 'Wavelength App',
        identifierType: 'app_bundle',
        identifierValue: 'com.wavelengthaudio.app',
        channels: ['streaming_audio'],
        tags: ['audio', 'music', 'streaming', 'mobile'],
      },
      {
        propertyId: 'wavelength_podcasts',
        name: 'Wavelength Podcast Network',
        identifierType: 'domain',
        identifierValue: 'podcasts.wavelengthaudio.example',
        channels: ['podcast'],
        tags: ['audio', 'podcast'],
      },
    ],
  },

  {
    id: 'streetlevel',
    name: 'StreetLevel Media',
    domain: 'streetlevelmedia.example',
    description: 'Urban digital out-of-home network operating 12,000+ screens across transit, retail, and city center locations in 50 metro areas.',
    channels: ['dooh', 'ooh'],
    deliveryTypes: ['guaranteed'],
    pricingTemplates: [
      {
        model: 'flat_rate', currency: 'USD', fixedPrice: 2500, minSpendPerPackage: 2500,
        doohParameters: { type: 'dooh', sov_percentage: 12.5, loop_duration_seconds: 480, min_plays_per_hour: 8 },
      },
      { model: 'cpm', currency: 'USD', fixedPrice: 8, minSpendPerPackage: 1000 },
      { model: 'time', currency: 'USD', fixedPrice: 800, timeParameters: { unit: 'week', min_duration: 1, max_duration: 52 } },
      {
        model: 'flat_rate', currency: 'GBP', fixedPrice: 2000, minSpendPerPackage: 2000,
        doohParameters: { type: 'dooh', sov_percentage: 12.5, loop_duration_seconds: 480, min_plays_per_hour: 8 },
      },
    ],
    measurementProvider: 'Geopath certified audience measurement',
    measurementNotes: 'Geopath-certified OOH impressions based on mobile location data. Audience composition via census integration.',
    reportingFrequencies: ['daily', 'monthly'],
    reportingMetrics: ['impressions', 'spend', 'reach'],
    properties: [
      {
        propertyId: 'streetlevel_transit',
        name: 'Transit Network',
        identifierType: 'domain',
        identifierValue: 'transit.streetlevelmedia.example',
        channels: ['dooh'],
        tags: ['dooh', 'transit', 'commuter'],
      },
      {
        propertyId: 'streetlevel_retail',
        name: 'Retail Screens',
        identifierType: 'domain',
        identifierValue: 'retail.streetlevelmedia.example',
        channels: ['dooh'],
        tags: ['dooh', 'retail', 'shopping'],
      },
      {
        propertyId: 'streetlevel_billboards',
        name: 'City Billboard Network',
        identifierType: 'domain',
        identifierValue: 'billboards.streetlevelmedia.example',
        channels: ['ooh'],
        tags: ['ooh', 'billboard', 'outdoor'],
      },
    ],
  },

  {
    id: 'playfield',
    name: 'Playfield Interactive',
    domain: 'playfield.example',
    description: 'In-game advertising platform integrated with 200+ mobile and console titles, reaching a global gaming audience of 85M monthly players.',
    channels: ['gaming', 'display'],
    deliveryTypes: ['non_guaranteed'],
    pricingTemplates: [
      { model: 'cpm', currency: 'USD', floorPrice: 10, priceGuidance: { suggested: 15, range: { min: 10, max: 25 } } },
      { model: 'cpcv', currency: 'USD', floorPrice: 0.03, priceGuidance: { suggested: 0.05, range: { min: 0.03, max: 0.10 } } },
    ],
    measurementProvider: 'IAS in-game viewability with Anzu SDK',
    measurementNotes: 'In-game impression tracking via SDK. Viewability measured per MRC in-game standards. Brand safety context derived from ESRB/PEGI ratings.',
    reportingFrequencies: ['daily'],
    reportingMetrics: ['impressions', 'spend', 'clicks', 'ctr', 'video_completions', 'completion_rate', 'viewability', 'engagement_rate'],
    properties: [
      {
        propertyId: 'playfield_mobile',
        name: 'Playfield Mobile Games',
        identifierType: 'app_bundle',
        identifierValue: 'com.playfield.games',
        channels: ['gaming', 'display'],
        tags: ['gaming', 'mobile', 'casual'],
      },
      {
        propertyId: 'playfield_console',
        name: 'Playfield Console & PC',
        identifierType: 'domain',
        identifierValue: 'console.playfield.example',
        channels: ['gaming'],
        tags: ['gaming', 'console', 'hardcore'],
      },
    ],
  },

  {
    id: 'shopgrid',
    name: 'ShopGrid',
    domain: 'shopgrid.example',
    description: 'Retail media network powering sponsored products and display advertising across a marketplace of 50K+ sellers and 200M monthly shoppers.',
    channels: ['retail_media', 'display'],
    deliveryTypes: ['non_guaranteed'],
    catalogTypes: ['product', 'store'],
    pricingTemplates: [
      { model: 'cpc', currency: 'USD', floorPrice: 0.80, priceGuidance: { suggested: 1.50, range: { min: 0.80, max: 4.00 } } },
      { model: 'cpm', currency: 'USD', floorPrice: 5, priceGuidance: { suggested: 8, range: { min: 5, max: 12 } } },
      { model: 'cpa', currency: 'USD', fixedPrice: 12, eventType: 'purchase' },
    ],
    measurementProvider: 'ShopGrid deterministic purchase attribution',
    measurementNotes: 'Deterministic purchase attribution from first-party shopper data. 14-day click-through, 1-day view-through window. ROAS available at SKU level.',
    reportingFrequencies: ['daily', 'monthly'],
    reportingMetrics: ['impressions', 'spend', 'clicks', 'ctr', 'conversions', 'conversion_value', 'roas', 'cost_per_acquisition', 'new_to_brand_rate'],
    properties: [
      {
        propertyId: 'shopgrid_web',
        name: 'ShopGrid Marketplace',
        identifierType: 'domain',
        identifierValue: 'shopgrid.example',
        channels: ['retail_media', 'display'],
        tags: ['retail', 'commerce', 'web'],
      },
      {
        propertyId: 'shopgrid_app',
        name: 'ShopGrid App',
        identifierType: 'app_bundle',
        identifierValue: 'com.shopgrid.shop',
        channels: ['retail_media', 'display'],
        tags: ['retail', 'commerce', 'mobile'],
      },
    ],
  },

  {
    id: 'viewpoint_sports',
    name: 'Viewpoint Sports',
    domain: 'viewpointsports.example',
    description: 'Live sports streaming platform with exclusive rights to major leagues, reaching 25M concurrent viewers during peak events.',
    channels: ['ctv', 'olv', 'linear_tv'],
    deliveryTypes: ['guaranteed'],
    pricingTemplates: [
      { model: 'cpm', currency: 'USD', fixedPrice: 35, minSpendPerPackage: 25000 },
      { model: 'flat_rate', currency: 'USD', fixedPrice: 75000, minSpendPerPackage: 75000 },
      { model: 'cpp', currency: 'USD', fixedPrice: 50000, cppParameters: { demographic: 'A25-54' } },
      { model: 'cpm', currency: 'EUR', fixedPrice: 32, minSpendPerPackage: 20000 },
    ],
    measurementProvider: 'Nielsen DAR with VideoAmp cross-screen',
    measurementNotes: 'Nielsen Digital Ad Ratings for demographic guarantee. VideoAmp cross-screen deduplication. Live sports viewability measured at 95%+ completion.',
    reportingFrequencies: ['daily', 'monthly'],
    reportingMetrics: ['impressions', 'spend', 'video_completions', 'completion_rate', 'reach', 'frequency', 'grps', 'viewability'],
    properties: [
      {
        propertyId: 'viewpoint_ctv',
        name: 'Viewpoint Sports CTV',
        identifierType: 'app_bundle',
        identifierValue: 'com.viewpointsports.ctv',
        channels: ['ctv'],
        tags: ['sports', 'live', 'ctv', 'premium'],
      },
      {
        propertyId: 'viewpoint_web',
        name: 'Viewpoint Sports Web',
        identifierType: 'domain',
        identifierValue: 'viewpointsports.example',
        channels: ['olv'],
        tags: ['sports', 'live', 'web'],
      },
    ],
  },

  {
    id: 'sparq_social',
    name: 'Sparq Social',
    domain: 'sparqsocial.example',
    description: 'Social platform with 300M monthly active users. Feed, stories, reels, and influencer-boosted placements across mobile and web.',
    channels: ['social', 'display', 'influencer'],
    deliveryTypes: ['non_guaranteed'],
    pricingTemplates: [
      { model: 'cpc', currency: 'USD', floorPrice: 0.50, priceGuidance: { suggested: 1.20, range: { min: 0.50, max: 3.00 } } },
      { model: 'cpm', currency: 'USD', floorPrice: 5, priceGuidance: { suggested: 9, range: { min: 5, max: 15 } } },
      { model: 'cpv', currency: 'USD', floorPrice: 0.01, priceGuidance: { suggested: 0.03, range: { min: 0.01, max: 0.08 } }, cpvParameters: { view_threshold: { type: 'duration', value: 2, unit: 'seconds' } } },
    ],
    measurementProvider: 'Sparq first-party analytics with DoubleVerify',
    measurementNotes: 'First-party engagement and conversion tracking. DoubleVerify brand safety and viewability. Cross-device identity graph for reach/frequency.',
    reportingFrequencies: ['daily', 'monthly'],
    reportingMetrics: ['impressions', 'spend', 'clicks', 'ctr', 'views', 'engagement_rate', 'reach', 'frequency', 'conversions'],
    properties: [
      {
        propertyId: 'sparq_app',
        name: 'Sparq App',
        identifierType: 'app_bundle',
        identifierValue: 'com.sparqsocial.app',
        channels: ['social', 'display', 'influencer'],
        tags: ['social', 'mobile', 'feed', 'stories', 'reels'],
      },
      {
        propertyId: 'sparq_web',
        name: 'Sparq Web',
        identifierType: 'domain',
        identifierValue: 'sparqsocial.example',
        channels: ['social', 'display'],
        tags: ['social', 'web'],
      },
    ],
  },

  {
    id: 'trendsettr',
    name: 'Trendsettr',
    domain: 'trendsettr.example',
    description: 'Creator and influencer marketplace connecting brands with 50K+ vetted creators across lifestyle, tech, beauty, fitness, and food verticals.',
    channels: ['influencer', 'social'],
    deliveryTypes: ['guaranteed'],
    pricingTemplates: [
      { model: 'flat_rate', currency: 'USD', fixedPrice: 5000, minSpendPerPackage: 2000 },
      { model: 'cpa', currency: 'USD', fixedPrice: 20, eventType: 'lead' },
    ],
    measurementProvider: 'Trendsettr attribution with CreatorIQ verification',
    measurementNotes: 'Creator content tracked via UTM + pixel. Engagement verified against platform APIs. Brand safety review of all creator content before publish.',
    reportingFrequencies: ['daily', 'monthly'],
    reportingMetrics: ['impressions', 'spend', 'engagement_rate', 'clicks', 'conversions', 'reach', 'views'],
    properties: [
      {
        propertyId: 'trendsettr_marketplace',
        name: 'Trendsettr Creator Network',
        identifierType: 'domain',
        identifierValue: 'trendsettr.example',
        channels: ['influencer', 'social'],
        tags: ['influencer', 'creator', 'ugc'],
      },
    ],
  },

  {
    id: 'beacon_search',
    name: 'Beacon Search',
    domain: 'beaconsearch.example',
    description: 'Search engine and shopping network with 180M monthly queries. Text ads, shopping listings, and keyword-targeted placements across web and mobile.',
    channels: ['search'],
    deliveryTypes: ['non_guaranteed'],
    catalogTypes: ['product'],
    pricingTemplates: [
      { model: 'cpc', currency: 'USD', floorPrice: 0.50, priceGuidance: { suggested: 2.50, range: { min: 0.50, max: 12.00 } } },
      { model: 'cpa', currency: 'USD', fixedPrice: 18, eventType: 'purchase' },
    ],
    measurementProvider: 'Beacon first-party conversion tracking',
    measurementNotes: 'Deterministic click-to-conversion attribution. 30-day click-through, 1-day view-through window. Keyword-level reporting with search term data.',
    reportingFrequencies: ['daily', 'monthly'],
    reportingMetrics: ['impressions', 'spend', 'clicks', 'ctr', 'conversions', 'conversion_value', 'cost_per_acquisition', 'roas'],
    properties: [
      {
        propertyId: 'beacon_web',
        name: 'Beacon Search Web',
        identifierType: 'domain',
        identifierValue: 'beaconsearch.example',
        channels: ['search'],
        tags: ['search', 'web', 'text_ads'],
      },
      {
        propertyId: 'beacon_shopping',
        name: 'Beacon Shopping',
        identifierType: 'domain',
        identifierValue: 'shopping.beaconsearch.example',
        channels: ['search'],
        tags: ['search', 'shopping', 'product_listing'],
      },
    ],
  },

  {
    id: 'novamind',
    name: 'NovaMind AI',
    domain: 'novamind.example',
    description: 'AI assistant platform with conversational ad placements, sponsored intelligence agents, and sponsored recommendations across 15M daily active users.',
    channels: ['display'],
    deliveryTypes: ['non_guaranteed', 'guaranteed'],
    pricingTemplates: [
      { model: 'cpm', currency: 'USD', floorPrice: 18, priceGuidance: { suggested: 30, range: { min: 18, max: 50 } } },
      { model: 'cpc', currency: 'USD', floorPrice: 2, priceGuidance: { suggested: 4, range: { min: 2, max: 8 } } },
      { model: 'cpa', currency: 'USD', fixedPrice: 8, eventType: 'agent_session' },
      { model: 'cpm', currency: 'USD', fixedPrice: 35, minSpendPerPackage: 10000 },
      { model: 'flat_rate', currency: 'USD', fixedPrice: 50000, minSpendPerPackage: 50000 },
    ],
    measurementProvider: 'NovaMind first-party analytics',
    measurementNotes: 'Conversation-context measurement. Engagement tracked via interaction depth (clicks, follow-up queries, conversions). Agent session duration and message count tracked per session. Viewability inherent in conversational surface.',
    reportingFrequencies: ['daily'],
    reportingMetrics: ['impressions', 'spend', 'clicks', 'ctr', 'engagement_rate', 'conversions'],
    properties: [
      {
        propertyId: 'novamind_assistant',
        name: 'NovaMind Assistant',
        identifierType: 'domain',
        identifierValue: 'novamind.example',
        channels: ['display'],
        tags: ['ai', 'conversational', 'assistant'],
      },
      {
        propertyId: 'novamind_recommendations',
        name: 'NovaMind Recommendations',
        identifierType: 'domain',
        identifierValue: 'recs.novamind.example',
        channels: ['display'],
        tags: ['ai', 'recommendations'],
      },
      {
        propertyId: 'novamind_travel',
        name: 'NovaMind Travel',
        identifierType: 'domain',
        identifierValue: 'travel.novamind.example',
        channels: ['display'],
        tags: ['ai', 'conversational', 'travel', 'assistant'],
      },
      {
        propertyId: 'novamind_shopping',
        name: 'NovaMind Shopping',
        identifierType: 'domain',
        identifierValue: 'shopping.novamind.example',
        channels: ['display'],
        tags: ['ai', 'conversational', 'shopping', 'commerce'],
      },
      {
        propertyId: 'novamind_wellness',
        name: 'NovaMind Wellness',
        identifierType: 'domain',
        identifierValue: 'wellness.novamind.example',
        channels: ['display'],
        tags: ['ai', 'conversational', 'health', 'wellness'],
      },
    ],
  },

  {
    id: 'crestline_radio',
    name: 'Crestline Radio Group',
    domain: 'crestlineradio.example',
    description: 'Terrestrial and streaming radio network with 35 stations across 20 markets, reaching 12M weekly listeners. Spot buys and sponsorships.',
    channels: ['radio', 'streaming_audio'],
    deliveryTypes: ['guaranteed'],
    pricingTemplates: [
      { model: 'cpp', currency: 'USD', fixedPrice: 3500, cppParameters: { demographic: 'A25-54' } },
      { model: 'flat_rate', currency: 'USD', fixedPrice: 8000, minSpendPerPackage: 8000 },
      { model: 'cpm', currency: 'USD', fixedPrice: 6, minSpendPerPackage: 2000 },
    ],
    measurementProvider: 'Nielsen Audio with Veritonic brand lift',
    measurementNotes: 'Nielsen Audio PPM measurement in metered markets. Diary in non-metered markets. Streaming impressions tracked via SDK. Spot verification via audio fingerprinting.',
    reportingFrequencies: ['monthly'],
    reportingMetrics: ['impressions', 'spend', 'reach', 'frequency', 'grps'],
    properties: [
      {
        propertyId: 'crestline_terrestrial',
        name: 'Crestline Terrestrial Stations',
        identifierType: 'domain',
        identifierValue: 'stations.crestlineradio.example',
        channels: ['radio'],
        tags: ['radio', 'terrestrial', 'local', 'broadcast'],
      },
      {
        propertyId: 'crestline_stream',
        name: 'Crestline Digital Streams',
        identifierType: 'domain',
        identifierValue: 'stream.crestlineradio.example',
        channels: ['streaming_audio'],
        tags: ['radio', 'streaming', 'digital'],
      },
    ],
  },

  {
    id: 'meridian_print',
    name: 'Meridian Print & Digital',
    domain: 'meridianmedia.example',
    description: 'Magazine and newspaper publisher with 8 print titles and companion digital editions. 4M combined print circulation, 25M monthly digital uniques.',
    channels: ['print', 'display'],
    deliveryTypes: ['guaranteed'],
    pricingTemplates: [
      { model: 'flat_rate', currency: 'USD', fixedPrice: 35000, minSpendPerPackage: 15000 },
      { model: 'cpm', currency: 'USD', fixedPrice: 22, minSpendPerPackage: 5000 },
      { model: 'time', currency: 'USD', fixedPrice: 12000, timeParameters: { unit: 'month', min_duration: 1, max_duration: 12 } },
    ],
    measurementProvider: 'Alliance for Audited Media (AAM) with comScore digital',
    measurementNotes: 'AAM-audited print circulation. comScore digital measurement. Print ad recall studies available quarterly. Digital viewability via IAS.',
    reportingFrequencies: ['monthly'],
    reportingMetrics: ['impressions', 'spend', 'reach'],
    properties: [
      {
        propertyId: 'meridian_magazines',
        name: 'Meridian Magazines',
        identifierType: 'domain',
        identifierValue: 'magazines.meridianmedia.example',
        channels: ['print'],
        tags: ['print', 'magazine', 'premium', 'lifestyle'],
      },
      {
        propertyId: 'meridian_digital',
        name: 'Meridian Digital Editions',
        identifierType: 'domain',
        identifierValue: 'digital.meridianmedia.example',
        channels: ['display'],
        tags: ['print', 'digital', 'companion'],
      },
    ],
  },
];
